pipeline {
    agent any
    environment {
        AWS_PROFILE = sh(script: 'aws iam list-account-aliases | jq .AccountAliases[0]', returnStdout: true)
    }
    parameters {
        choice choices: ['us-east1'], description: '', name: 'AWS_REGION'
    }
    stages {
        stage('Plan') {
            steps {
                sh "terraform --version"
                sh "./hosting/tf-init.sh"
                sh "./hosting/tf-plan.sh"
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}