import java.util.UUID
def shellCommandOutput(command) {
    def uuid = UUID.randomUUID()
    def filename = "cmd-${uuid}"
    echo filename
    sh ("${command} > ${filename}")
    def result = readFile(filename).trim()
    sh "rm ${filename}"
    return result
}

// Get the Terraform tool.
def tfHome = tool name: 'Terraform', type: 'com.cloudbees.jenkins.plugins.customtools.CustomTool'

wrap([$class: 'AnsiColorBuildWrapper', colorMapName: 'xterm']) {
    pipeline {
        agent any


        environment {
            AWS_PROFILE = shellCommandOutput("aws iam list-account-aliases | jq .AccountAliases[0]")
            PATH = "${tfHome}:${env.PATH}"
        }
        parameters {
            choice choices: ['us-east1'], description: '', name: 'AWS_REGION'
        }
        stages {
            stage('Plan') {
                steps {
                    sh "terraform --version"
                    sh "terraform --version"
                }
            }
            stage('Test') {
                steps {
                    echo 'Testing..'
                }
            }
            stage('Deploy') {
                steps {
                    echo 'Deploying....'
                }
            }
        }
    }
}